# Generated by Django 4.1.4 on 2023-02-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_unconfirmed_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unconfirmed_email',
            field=models.EmailField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
