version: '3.8'
services:
  proxy:
    build: docker_config/proxy
    restart: always
    ports:
      - 80:80
    networks:
      - django_network

  db:
    build: docker_config/postgres
    # image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      - PG_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PG_DB=django_db
      - PG_HOST=db
      - PG_PORT=5432
    networks:
      - django_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    environment:
      - DEBUG=0
      - ENV=prod
      ## postgres config
      - PG_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PG_DB=django_db
      - PG_HOST=db
      - PG_PORT=5432
      ## Sending email config
      - EMAIL_HOST=smtp.googlemail.com
      - EMAIL_PORT=25
      - EMAIL_USE_TLS=1
      #  set a real email
      - EMAIL_HOST_USER=fake@mail.com
    networks:
      - django_network


networks:
  django_network:

volumes:
  postgres_data: